version: '3'

services:
  cms-app:    
    build: ./cms-app
    command: ./wait-for-it.sh cms-db:5432 -- bash /root/docker-entrypoint.sh
    volumes:
      - ./cms-app/docker-entrypoint.sh:/root/docker-entrypoint.sh:ro
      - ./cms-app/config:/root/cms/config:ro
      - ./cms-course:/root/cms-data/cms-course
      - ./cms-logs:/var/log/cms
    depends_on:
      - cms-db
    restart: unless-stopped

  nginx:
    image: nginx
    ports:
       - "80:80"
       - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/cms.key:/etc/nginx/certs/cms.key:ro
      - ./nginx/cms.crt:/etc/nginx/certs/cms.crt:ro
    restart: unless-stopped

  cms-db:
    image: postgres:12.0-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=cmsuser
      - POSTGRES_PASSWORD=cmspass
      - POSTGRES_DB=cms_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./postgres/initdb.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
